import { Code, ExternalLink, Github, Link, UserIcon } from "lucide-react";

const myData = {
  name: "Lazaro Rodriguez Leyva",
  role: "Desarrollador Frontend",
  description:
    " Desarrollador Frontend apasionado por crear experiencias web increibles",
  resumeUrl: "/path/to/resume.pdf",
  socialLinks: {
    github: "https://github.com/lrodriguez05/",
    linkedin: "https://www.linkedin.com/in/lazaro-rodriguez-leyva/",
    email: "lazarorodriguezleyva@gmail.com",
  },
  aboutMe: [
    {
      title: "Desarrollo Frontend",
      description: "Especializado en React, JavaScript y CSS moderno",
      Icon: Code,
      colorIcon: "#2563eb",
      bgIcon: "bg-blue-100",
    },
    {
      title: "Diseño UI/UX",
      description: "Creo interfaces intuitivas y atractivas para usuarios",
      Icon: UserIcon,
      colorIcon: "#16a34a",
      bgIcon: "bg-green-100",
    },
    {
      title: "Responsive Design",
      description:
        "Sitios web que funcionan perfectamente en cualquier dispositivo",
      Icon: Code,
      colorIcon: "#2563eb",
      bgIcon: "bg-blue-100",
    },
  ],
  skills: [
    {
      bgColor: "bg-blue-600",
      color: "text-white",
      progressColor: "bg-white",
      name: "ReactJS",
      icon: Code,
      description:
        "Mi especialidad y framework favorito para desarrollo frontend",
      percentage: 85,
      rowPosition: "row-span-2",
      colPosition: "col-span-2",
      border: "",
      borderColor: "",
    },
    {
      bgColor: "bg-orange-50",
      color: "text-orange-500",
      name: "HTML",
      icon: "",
      description: "",
      percentage: 90,
      progressColor: "bg-orange-500",
      rowPosition: "",
      colPosition: "",
      border: "border-l-4",
      borderColor: "border-orange-500",
    },
    {
      bgColor: "bg-blue-50",
      color: "text-blue-500",
      name: "CSS",
      icon: "",
      description: "",
      percentage: 85,
      progressColor: "bg-blue-500",
      rowPosition: "",
      colPosition: "",
      border: "border-l-4",
      borderColor: "border-blue-500",
    },
    {
      bgColor: "bg-yellow-50",
      color: "text-yellow-500",
      name: "JavaScript",
      icon: Code,
      description: "",
      percentage: 85,
      iconPosition: "bottom",
      progressColor: "bg-yellow-500",
      rowPosition: "row-span-2",
      colPosition: "",
      border: "border-l-4",
      borderColor: "border-yellow-500",
    },
    {
      bgColor: "bg-green-50",
      color: "text-green-500",
      name: "Node.js",
      icon: "",
      description: "",
      percentage: 70,
      progressColor: "!bg-green-500",
      rowPosition: "row-span-2",
      colPosition: "",
      border: "border-l-4",
      borderColor: "border-green-500",
    },
    {
      bgColor: "bg-purple-50",
      color: "text-purple-500",
      name: "Git",
      icon: "",
      description: "",
      percentage: 85,
      progressColor: "bg-purple-500",
      rowPosition: "",
      colPosition: "col-span-2",
      border: "border-l-4",
      borderColor: "border-purple-500",
    },
    {
      bgColor: "bg-indigo-50",
      color: "text-indigo-500",
      name: "TailWindCSS",
      icon: "",
      description: "Framework CSS que uso diariamente",
      percentage: 85,
      progressColor: "bg-indigo-500",
      rowPosition: "",
      colPosition: "col-span-2",
      border: "border-l-4",
      borderColor: "border-indigo-500",
    },
    {
      bgColor: "bg-red-50",
      color: "text-red-500",
      name: "SQLite",
      icon: "",
      description: "",
      percentage: 85,
      progressColor: "bg-red-500",
      rowPosition: "",
      colPosition: "col-span-2",
      border: "border-l-4",
      borderColor: "border-red-500",
    },
    {
      bgColor: "bg-teal-50",
      color: "text-teal-500",
      name: "TypeScript",
      icon: "",
      description: "",
      percentage: 85,
      progressColor: "bg-teal-500",
      rowPosition: "",
      colPosition: "col-span-2",
      border: "border-l-4",
      borderColor: "border-teal-500",
    },
  ],
  projectsCards: [
    {
      bgFrom: "from-blue-400",
      bgTo: "to-purple-600",
      bgColor: "bg-blue-600",
      gradientDir: "br",
      Icon: Code,
      title: "Proyecto de Libreria potenciado por IA",
      description: "Una web para gestionar una libreria con asistente de IA",
      tech: ["ReactJS", "TailwindCSS", "SQLite"],
      social: [
        { icon: Github, link: "https://github.com/lrodriguez05/library-front" },
        {
          icon: ExternalLink,
          link: "https://library-front-cyan.vercel.app/login",
        },
      ],
      rowPosition: "",
      colPosition: "col-span-1",
      colCondition: "sm:col-span-2",
      bgHeight: "h-48",
      IconSize: 64,
    },
    {
      bgFrom: "from-green-400",
      bgTo: "to-blue-500",
      bgColor: "bg-blue-600",
      gradientDir: "r",
      Icon: Code,
      title: "Proyecto Chat",
      description: "Web de chat con Socket.io y ReactJS",
      tech: ["ReactJS", "Socket.io"],
      social: [
        { icon: Github, link: "https://github.com/lrodriguez05/chat-client" },
        {
          icon: ExternalLink,
          link: "https://chat-client-dusky.vercel.app/login",
        },
      ],
      rowPosition: "",
      colPosition: "",
      bgHeight: "h-32",
      IconSize: 48,
    },
    {
      bgFrom: "from-purple-400",
      bgTo: "to-pink-500",
      bgColor: "bg-blue-600",
      gradientDir: "r",
      Icon: Code,
      title: "CV",
      description: "Mi curriculum vitae interactivo",
      tech: ["TypeScript", "TailwindCSS"],
      social: [
        { icon: Github, link: "https://github.com/lrodriguez05/me-cv" },
        { icon: ExternalLink, link: "https://me-cv-kappa.vercel.app/" },
      ],
      rowPosition: "",
      colPosition: "",
      bgHeight: "h-32",
      IconSize: 48,
    },
    {
      bgFrom: "from-pink-400",
      bgTo: "to-yellow-500",
      bgColor: "bg-blue-600",
      gradientDir: "r",
      Icon: Code,
      title: "To-Do App",
      description: "Aplicacion de tareas con React Hoocks",
      tech: ["CSS"],
      social: [
        { icon: Github, link: "https://github.com/lrodriguez05/todo-app" },
        { icon: ExternalLink, link: "https://lrodriguez05.github.io/todo-app" },
      ],
      rowPosition: "",
      colPosition: "",
      bgHeight: "h-32",
      IconSize: 48,
    },
  ],
};

export default myData;
